# Generated by Django 3.1.5 on 2021-01-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=225, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=225, verbose_name='密码')),
                ('created_date', models.DateTimeField(verbose_name='item created time')),
                ('updated_date', models.DateTimeField(verbose_name='item update time')),
            ],
        ),
    ]
