# Generated by Django 3.1.5 on 2021-01-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
