# Generated by Django 3.1.5 on 2021-01-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210106_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='', max_length=255, verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='--', max_length=255, verbose_name='用户昵称'),
        ),
    ]
